#if UNITY_EDITOR && UNITY_IOS
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEngine;

// Runtime SDKs are optional. All native dependencies and project changes live in the SDK export only.
public sealed class DifferenceSdkIosBuild : IPreprocessBuildWithReport
{
    public const string MinimumIosVersion = "15.0"; // Facebook 6.22 and DT Exchange 8.4.10 require iOS 15.
    const string PodfileHeader = "# Generated by DifferenceSdkIosBuild.\n";
    const string FirebasePlist = "GoogleService-Info.plist";
    const string MaxPlist = "AppLovin-Settings.plist";
    const string SkAdNetworkFile = "SdkDependencies/iOS/SKAdNetworkIds.txt";
    const string CrashlyticsScript = "\"${PODS_ROOT}/FirebaseCrashlytics/run\"";
    public int callbackOrder => -900;

    // Versions from jigsawpuzzle christmas2026/SDK, including its eleven MAX mediation adapters.
    const string Pods = @"  pod 'Adjust', '5.3.0'
  pod 'Firebase/Core', '11.10.0'
  pod 'Firebase/Analytics', '11.10.0'
  pod 'Firebase/Crashlytics', '11.10.0'
  pod 'Firebase/Messaging', '11.10.0'
  pod 'Firebase/RemoteConfig', '11.10.0'
  pod 'AppLovinSDK', '13.6.4'
  pod 'Google-Mobile-Ads-SDK', '13.8.0'
  pod 'GoogleUserMessagingPlatform', '3.1.0'
  pod 'AppLovinMediationByteDanceAdapter', '8.2.1.0.0'
  pod 'AppLovinMediationFacebookAdapter', '6.22.0.1'
  pod 'AppLovinMediationGoogleAdapter', '13.8.0.0'
  pod 'AppLovinMediationInMobiAdapter', '11.4.1.2'
  pod 'AppLovinMediationMintegralAdapter', '8.1.7.0.0'
  pod 'AppLovinMediationUnityAdsAdapter', '4.20.0.0'
  pod 'AppLovinMediationVungleAdapter', '7.7.7.0'
  pod 'AppLovinMediationBidMachineAdapter', '3.8.0.0.0'
  pod 'AppLovinMediationFyberAdapter', '8.4.10.0'
  pod 'AppLovinMediationChartboostAdapter', '9.14.0.0'
  pod 'AppLovinMediationIronSourceAdapter', '9.6.0.0.0'
";

    public void OnPreprocessBuild(BuildReport report)
    {
        if (report.summary.platform != BuildTarget.iOS) return;
        bool enabled = DifferenceSdkBuild.Enabled(BuildTarget.iOS);
        ValidateOutputFolder(report.summary.outputPath, enabled);
        if (!enabled) return;
        DifferenceSdkBuild.Validate(BuildTarget.iOS);
        ReadFirebaseConfig(DifferenceSdkSettings.instance.iosGoogleServicesPlist,
            PlayerSettings.GetApplicationIdentifier(BuildTargetGroup.iOS));
        if (!Version.TryParse(PlayerSettings.iOS.targetOSVersionString, out var version) ||
            version < new Version(MinimumIosVersion))
            throw new BuildFailedException("SDK 包最低支持 iOS 15.0。请使用 Mobile Build (SDK) 窗口导出，或调整 Target minimum iOS Version。");
    }

    static void ValidateOutputFolder(string path, bool sdkEnabled)
    {
        if (sdkEnabled || string.IsNullOrEmpty(path)) return;
        var podfile = Path.Combine(path, "Podfile");
        if (File.Exists(Path.Combine(path, MaxPlist)) ||
            (File.Exists(podfile) && File.ReadAllText(podfile).StartsWith(PodfileHeader, StringComparison.Ordinal)))
            throw new BuildFailedException("普通包不能覆盖已有 SDK 的 Xcode 导出目录。请选择新的空目录，避免旧 Pods、Framework 和配置残留。");
    }

    [PostProcessBuild(1000)]
    public static void OnPostProcessBuild(BuildTarget target, string path)
    {
        if (target != BuildTarget.iOS || !DifferenceSdkBuild.Enabled(target)) return;
        DifferenceSdkBuild.Validate(target);
        var settings = DifferenceSdkSettings.instance;
        ConfigureExport(path, settings.iosGoogleServicesPlist, settings.iosMaxSdkKey, settings.iosAdMobAppId,
            settings.iosTrackingDescription, PlayerSettings.GetApplicationIdentifier(BuildTargetGroup.iOS),
            PlayerSettings.iOS.targetOSVersionString);
        Debug.Log("iOS SDK 依赖已写入导出目录。在 Mac 上运行 pod install --repo-update，然后打开 Unity-iPhone.xcworkspace 编译和签名。");
    }

    static PlistDocument ReadFirebaseConfig(string path, string bundleId)
    {
        var config = new PlistDocument();
        config.ReadFromFile(DifferenceSdkBuild.ConfigPath(path));
        foreach (var key in new[] { "BUNDLE_ID", "GOOGLE_APP_ID", "GCM_SENDER_ID", "PROJECT_ID", "API_KEY" })
            if (!config.root.values.TryGetValue(key, out var value) || string.IsNullOrWhiteSpace(value.AsString()))
                throw new BuildFailedException("GoogleService-Info.plist 缺少有效的 " + key + "。");
        if (config.root["BUNDLE_ID"].AsString() != bundleId)
            throw new BuildFailedException("GoogleService-Info.plist 的 BUNDLE_ID 与当前 iOS Bundle Identifier 不一致。");
        return config;
    }

    // Separate from the build callback so the same transformation can be checked against Unity's Xcode template.
    static void ConfigureExport(string path, string firebaseConfig, string maxSdkKey, string adMobAppId,
        string trackingDescription, string bundleId, string minimumVersion)
    {
        firebaseConfig = DifferenceSdkBuild.ConfigPath(firebaseConfig);
        ReadFirebaseConfig(firebaseConfig, bundleId);
        var podfile = Path.Combine(path, "Podfile");
        if (File.Exists(podfile) && !File.ReadAllText(podfile).StartsWith(PodfileHeader, StringComparison.Ordinal))
            throw new BuildFailedException("导出目录已有其他 Podfile。请导出到新的空目录，避免覆盖现有原生依赖。");
        var projectPath = PBXProject.GetPBXProjectPath(path);
        var project = new PBXProject();
        project.ReadFromFile(projectPath);
        var mainTarget = project.GetUnityMainTargetGuid();
        var frameworkTarget = project.GetUnityFrameworkTargetGuid();
        if (string.IsNullOrEmpty(mainTarget) || string.IsNullOrEmpty(frameworkTarget))
            throw new BuildFailedException("Xcode 工程缺少 Unity-iPhone 或 UnityFramework Target。");

        File.Copy(firebaseConfig, Path.Combine(path, FirebasePlist), true);
        AddResource(project, mainTarget, FirebasePlist);
        var max = new PlistDocument();
        max.root.SetString("SdkKey", maxSdkKey);
        max.root.CreateDict("ConsentFlowInfo").SetBoolean("ConsentFlowEnabled", false); // UMP owns the consent flow.
        max.WriteToFile(Path.Combine(path, MaxPlist));
        AddResource(project, mainTarget, MaxPlist);

        var plistPath = Path.Combine(path, "Info.plist");
        var plist = new PlistDocument();
        plist.ReadFromFile(plistPath);
        plist.root.SetString("GADApplicationIdentifier", adMobAppId);
        plist.root.SetString("NSUserTrackingUsageDescription", trackingDescription);
        plist.root.SetBoolean("FirebaseAppDelegateProxyEnabled", true);
        AddSkAdNetworks(plist);
        plist.WriteToFile(plistPath);

        foreach (var target in new[] { mainTarget, frameworkTarget })
        {
            project.UpdateBuildProperty(target, "OTHER_LDFLAGS", new[] { "-ObjC", "-lc++" }, null);
            project.SetBuildProperty(target, "GCC_ENABLE_OBJC_EXCEPTIONS", "YES");
            project.SetBuildProperty(target, "CLANG_ENABLE_MODULES", "YES");
            project.SetBuildProperty(target, "ENABLE_BITCODE", "NO");
            project.SetBuildProperty(target, "ENABLE_USER_SCRIPT_SANDBOXING", "NO");
            project.SetBuildProperty(target, "IPHONEOS_DEPLOYMENT_TARGET", minimumVersion);
        }
        foreach (var framework in new[] { "AdSupport.framework", "AdServices.framework", "StoreKit.framework", "AppTrackingTransparency.framework" })
            project.AddFrameworkToProject(frameworkTarget, framework, true);
        project.AddFrameworkToProject(mainTarget, "UserNotifications.framework", false);
        project.SetBuildProperty(frameworkTarget, "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES", "NO");
        project.SetBuildProperty(mainTarget, "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES", "YES");
        project.SetBuildProperty(frameworkTarget, "SWIFT_VERSION", "5.0");
        const string swiftFile = "Classes/DifferenceSdkSwiftSupport.swift";
        Directory.CreateDirectory(Path.Combine(path, "Classes"));
        File.WriteAllText(Path.Combine(path, swiftFile), "// Ensures Swift runtime support for mediated SDKs.\nimport Foundation\n");
        AddResource(project, frameworkTarget, swiftFile);

        if (string.IsNullOrEmpty(project.GetShellScriptBuildPhaseForTarget(mainTarget, "Firebase Crashlytics", "/bin/sh", CrashlyticsScript)))
            project.AddShellScriptBuildPhase(mainTarget, "Firebase Crashlytics", "/bin/sh", CrashlyticsScript,
                new List<string> { "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}",
                    "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}",
                    "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist",
                    "$(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist", "$(TARGET_BUILD_DIR)/$(EXECUTABLE_PATH)" });
        project.WriteToFile(projectPath);
        var entitlements = project.GetBuildPropertyForAnyConfig(mainTarget, "CODE_SIGN_ENTITLEMENTS");
        if (string.IsNullOrEmpty(entitlements)) entitlements = "Unity-iPhone/DifferenceSdk.entitlements";
        Directory.CreateDirectory(Path.GetDirectoryName(Path.Combine(path, entitlements)));
        var capabilities = new ProjectCapabilityManager(projectPath, entitlements, targetGuid: mainTarget);
        capabilities.AddPushNotifications(false);
        capabilities.AddBackgroundModes(BackgroundModesOptions.RemoteNotifications);
        capabilities.WriteToFile();

        File.WriteAllText(podfile, CreatePodfile(minimumVersion), new UTF8Encoding(false));
        VerifyExport(path);
    }

    static void AddResource(PBXProject project, string target, string file)
    {
        var guid = project.FindFileGuidByProjectPath(file);
        if (string.IsNullOrEmpty(guid)) guid = project.AddFile(file, file, PBXSourceTree.Source);
        project.AddFileToBuild(target, guid);
    }

    static void AddSkAdNetworks(PlistDocument plist)
    {
        var array = plist.root.values.TryGetValue("SKAdNetworkItems", out var existing)
            ? existing.AsArray() : plist.root.CreateArray("SKAdNetworkItems");
        var ids = new HashSet<string>(array.values.Select(v => v.AsDict()["SKAdNetworkIdentifier"].AsString()));
        foreach (var id in File.ReadAllLines(SkAdNetworkFile).Select(v => v.Trim()).Where(v => v.Length > 0 && !v.StartsWith("#")))
        {
            if (!System.Text.RegularExpressions.Regex.IsMatch(id, @"^[a-z0-9]{10}\.skadnetwork$"))
                throw new BuildFailedException("SKAdNetworkIds.txt 中存在无效标识。");
            if (ids.Add(id)) array.AddDict().SetString("SKAdNetworkIdentifier", id);
        }
    }

    // MAX's selected SDK versions contain four dynamic frameworks. Declaring their pods on the app
    // target lets CocoaPods embed/sign them there, instead of nesting them in UnityFramework.framework.
    static string CreatePodfile(string minimumVersion) => PodfileHeader +
        "source 'https://cdn.cocoapods.org/'\nplatform :ios, '" + minimumVersion + @"'
use_frameworks! :linkage => :static
project 'Unity-iPhone.xcodeproj'
target 'UnityFramework' do
" + Pods + @"end

target 'Unity-iPhone' do
  pod 'AppLovinSDK', '13.6.4'
  pod 'FBAudienceNetwork', '6.22.0'
  pod 'InMobiSDK', '11.4.1'
  pod 'AppLovinMediationChartboostAdapter', '9.14.0.0'
end
";

    static void VerifyExport(string path)
    {
        var project = new PBXProject();
        project.ReadFromFile(PBXProject.GetPBXProjectPath(path));
        var plist = new PlistDocument();
        plist.ReadFromFile(Path.Combine(path, "Info.plist"));
        if (plist.root["SKAdNetworkItems"].AsArray().values.Count < 100 ||
            string.IsNullOrEmpty(project.FindFileGuidByProjectPath(FirebasePlist)) ||
            string.IsNullOrEmpty(project.FindFileGuidByProjectPath(MaxPlist)) ||
            !File.ReadAllText(Path.Combine(path, "Podfile")).Contains("pod 'Firebase/Crashlytics', '11.10.0'") ||
            project.GetBuildPropertyForAnyConfig(project.GetUnityFrameworkTargetGuid(), "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES") != "NO")
            throw new BuildFailedException("iOS SDK 导出内容校验失败。");
    }

    [MenuItem("Tools/Find Differences/Check iOS SDK Export Setup")]
    public static void CheckExportSetup()
    {
        var path = Path.GetFullPath(Path.Combine("Temp", "DifferenceSdkIosCheck-" + Guid.NewGuid().ToString("N")));
        var template = Path.Combine(EditorApplication.applicationContentsPath, "PlaybackEngines/iOSSupport/Trampoline");
        Directory.CreateDirectory(Path.Combine(path, "Unity-iPhone.xcodeproj"));
        File.Copy(Path.Combine(template, "Unity-iPhone.xcodeproj/project.pbxproj"), PBXProject.GetPBXProjectPath(path));
        File.Copy(Path.Combine(template, "Info.plist"), Path.Combine(path, "Info.plist"));
        var input = new PlistDocument();
        foreach (var key in new[] { "GOOGLE_APP_ID", "GCM_SENDER_ID", "PROJECT_ID", "API_KEY" }) input.root.SetString(key, "test-only");
        input.root.SetString("BUNDLE_ID", "com.example.sdkcheck");
        var config = Path.Combine(path, "TestFirebase.plist");
        input.WriteToFile(config);
        ConfigureExport(path, config, "test-only", "ca-app-pub-3940256099942544~1458002511", "Test permission", "com.example.sdkcheck", MinimumIosVersion);
        ConfigureExport(path, config, "test-only", "ca-app-pub-3940256099942544~1458002511", "Test permission", "com.example.sdkcheck", MinimumIosVersion);
        bool rejected = false;
        try { ReadFirebaseConfig(config, "com.example.wrong"); }
        catch (BuildFailedException) { rejected = true; }
        if (!rejected) throw new BuildFailedException("Bundle ID mismatch was not rejected.");
        rejected = false;
        try { ValidateOutputFolder(path, false); }
        catch (BuildFailedException) { rejected = true; }
        if (!rejected) throw new BuildFailedException("Plain export accepted a directory containing an old SDK export.");
        Debug.Log("iOS SDK export setup PASS: native project, Podfile, plist, repeated export, mismatched Bundle ID and plain export isolation. " + path);
    }
}
#endif
