    maven { url "https://artifactory.bidmachine.io/bidmachine" }
    maven { url "https://cboost.jfrog.io/artifactory/chartboost-ads/" }
    maven { url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" }
    maven { url "https://artifact.bytedance.com/repository/pangle" }
